### ISSUE TITLE
Apple GPU support

### ISSUE THREAD

**Issue by OutisLi** [celeritas-project/celeritas#1528]
will this project realize metal support for apple silicon?

**Comment by sethrj** [comment]
Hi @OutisLi , I've had "Apple Metal" support informally on my wish list for a while, but there's two reasons we haven't considered it.

First is simply priority: since no supercomputers (and to my knowledge in the HEP community, no grid clusters) are based on apple ARM chips, we haven't been able to dedicate the person-power because our first goal is accelerating large-scale problems rather than the ones that are run on a laptop.

Second is technical: if you look at the [Metal shader language](https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf) limitations and data types, the are three big features we use in Celeritas that are unallowable in MSL (in decreasing importance):
- lambda expressions
- double precision
- derived classes
- noexcept operator

The lack of lambdas is a killer; we'd have to refactor a substantial amount of code (and make it less clean in the process).

That said, we're always interested in working with contributors to explore new and exciting ideas. I've added this to our "potential projects" page. If you're interested in trying this yourself, I'd recommend playing around with the "demo interactor" (by reverting #1463 or rewinding all the way back to 588cca0597c6fb336ea7be72a7913c39173ce7f2) since that's the simplest "interesting" GPU problem that we ran.

Please let us know if you're interested in exploring that semi-independently; if not, I'll close this issue and leave the "future projects" bullet in place as a reminder. Cheers!

**Comment by OutisLi** [comment]
Thanks for your reply. I am currently a student in physics in Peking University. Some of my researches include using Geant4. Even thought I have access to the HPC in our school, however I personal would like to try using Mac to do the calculations. I found that thanks to the high performance in single core in apple m4 chip, the basic Mac mini can beat 32 core intel processors(it could also be that the cpu of our HPC is too slow). I developed a self-defined physicslist in Geant4 to do my research, however, I want to utilize the gpu to do some calculations in my physicslist, that's how I found your project. Since you said it is difficult to migrate to metal, is it possible for me to utilize metal in my physicslist? Thanks a lot.

**Comment by sethrj** [comment]
Well, using a coprocessor is not quite that simple. First, since we're not directly using Geant4 physics code, we have to have the physics models implemented inside Celeritas in a GPU-friendly way. This is currently only done for certain processes on electron/positron/gamma. If you're using only those processes, then you can directly use Celeritas (on CPU or GPU). Then to use Metal we would have to adapt the CUDA/HIP GPU kernels to use Apple's metal shading language, which as I said isn't trivial.

So if your primary interest is accelerating physics simulations in the near term, rather than exploring novel uses of GPU programming, we're not yet at the stage where we can make the mac any faster. If you're just interested in accelerating the physics, then depending on what scoring you have for you problem, Celeritas on CPU might be able to speed it up: we're about 20% faster than Geant4 on some problems and we could potentially increase that number further.

**Comment by OutisLi** [comment]
> Well, using a coprocessor is not quite that simple. First, since we're not directly using Geant4 physics code, we have to have the physics models implemented inside Celeritas in a GPU-friendly way. This is currently only done for certain processes on electron/positron/gamma. If you're using only those processes, then you can directly use Celeritas (on CPU or GPU). Then to use Metal we would have to adapt the CUDA/HIP GPU kernels to use Apple's metal shading language, which as I said isn't trivial.
> 
> So if your primary interest is accelerating physics simulations in the near term, rather than exploring novel uses of GPU programming, we're not yet at the stage where we can make the mac any faster. If you're just interested in accelerating the physics, then depending on what scoring you have for you problem, Celeritas on CPU might be able to speed it up: we're about 20% faster than Geant4 on some problems and we could potentially increase that number further.

Thanks for your reply, I decide to explore how to move some of my calculations to gpu in Geant4, since my code is somehow complicated and will cost much time to migrate to Celeritas. However, thanks for your suggestions again for telling me that metal may not be well suited.

**Comment by sethrj** [comment]
We've worked hard to make the "migration" to Celeritas as easy as possible, but since we're mostly working with LHC simulations we recognize it might not be the best solution for you. If you do want to try to integrate Celeritas, please let us know what difficulties you encounter. And we'll reopen this issue if Apple Metal is to be considered in the future. Cheers!
