### ISSUE TITLE
Ensure material/volume ID consistency between Geant and VecGeom

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#223]
The `geant-exporter` constructs `ImportVolume` objects using logical volume ID (aka "unplaced" volumes in VecGeom nomenclature). In contrast, GeoParams/GeoTrackView use *physical* IDs. It's also unclear how the IDs depend on the front-end and parser, whether they're consistent across readers and versions. For example, I think #192 demonstrated that the physical IDs change depending on whether ROOT or VGDML is constructing the geometry.

We need to be able to guarantee that the material/cutoff IDs are consistent between the geant exporter and the VecGeom definition, and that we're consistently using physical/logical IDs.
- Do we only need logical volume IDs? Or will detector applications require physical IDs as part of the interface?
- Can we use the volume names to guarantee the correct mapping between applications/libraries?
- Should we rely on https://gitlab.cern.ch/VecGeom/VecGeom/-/merge_requests/805 for pulling in the vecgeom data?

@stognini @mrguilima @pcanal

**Comment by stognini** [comment]
Update on ongoing work:

1. Tested 4 different geometries being constructed `programmatically` and via the `G4GDMLParser`. This leads to one discrepancy:
- The `world` volume has its `InstanceID` defined at its creation time if the geometry is constructed programmatically, but it is always stored last when saved into a gdml file. This results in a shifted list of volume ids when each case is compared.

Not an issue, since materia_ids **do not** change, and the link `volume_id -> material_id` is kept in place.

2. Tested loading each one of the aforementioned gdml files using VecGeom's `vgdml::Frontend::Load(...)` and compared the loaded volume_ids from VecGeom with the expected volume_ids from `G4GDMLParser`. They match.

I am not sure if the `volume_id` is the only needed piece for VecGeoms navigator to work, but since the volume ids match, we should be able to correctly retrieve any needed information:

Get the logical volume_id from a given placed volume using VecGeom; from our imported data at startup, we can now: check what is the material_id associated to that logical volume; use said material_id to fetch the corresponding XS data in the physics tables.

**Comment by sethrj** [comment]
Currently the geometry (GeoParams and GeoTrackView) return placed ("physical") volume IDs, so we need to change these to unplaced ("logical") IDs.  @mrguilima will handle that.
