### ISSUE TITLE
CPU demo loop

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#263]
Although most of the core Celeritas components are platform-agnostic, a lot of the glue code (e.g. `Model::interact` and detail::rayleigh_interact) are GPU/CUDA-specific. To compare CPU apples to GPU apples, we should support a full event loop on the CPU with celeritas. At first blush, this will mostly be copying code from e.g. `KleinNishina.cu` to `.cc`, taking host pointers instead of device.

**Comment by paulromano** [comment]
One issue I've run into with trying to run the demo loop on CPU: right now, the problem consists of 15 primaries but we're only setting room in the state data for a single primary:
https://github.com/celeritas-project/celeritas/blob/b62d8275c49804fd772bc7063e40fc13a78a515b/app/demo-loop/LDemoRun.cc#L190
It looks like this is because `VGNavCollection` on the host only permits its size to be one, so increasing the above size just leads to precondition errors on the size of the navigation state. From what I can gather, the options to get around this are:
1. Use `NavStatePool` on host as we currently do for device to allow multiple CPU "threads"
2. Extend the demo loop logic to account for the case where # primaries > # tracks (not yet implemented for GPU), and continue with a single primary on CPU

Any thoughts on the best path forward would be appreciated

**Comment by amandalund** [comment]
Do we need space for more than one track state on the CPU? Seems like we would have an outer loop over primaries and initialize the track from each primary/transport it one by one. The track initialization code (`extend_from_primaries`, `initialize_tracks`, `extend_from_secondaries`) is all device-specific, so we'll different logic on the CPU anyway.

**Comment by paulromano** [comment]
The way I've been structuring things so far is to have a loop over thread IDs when adding an equivalent CPU "kernel", e.g.
https://github.com/paulromano/celeritas/blob/a611b0ba8adc23d56e8d086a6552153ed8678af9/src/physics/em/detail/KleinNishina.cc#L32-L33

This exposes some loop-level parallelism so that if we wanted to actually use CPU threads, it would be pretty straightforward. The alternative would be for the CPU kernels to omit that loop and instead have an outer loop over primaries, as you suggest. Either way, we'll need to have an outer loop for the case where # primaries > # tracks, so the question is really just on the inner loop do we want to allow more than one primary/track?

**Comment by sethrj** [comment]
I think either approach would be fine, but single-threaded should be our initial goal and I will approve most expedients to get us there. :)

**Comment by sethrj** [comment]
Closed by #273 and #310
