### ISSUE TITLE
Add process/element cross section calculation and sampling

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#60]
Many of the physics interactions have to sample an interacting atom (by cross section) because the physics depends on the nuclear charge, etc. Both Shift and Geant4 do this, but with notable differences:
- Geant4 precalculates energy-dependent cross sections per process and integrates over elements in each material. In contrast, Shift's AMPX data (entirely precalculated) is integrated over processes (MT numbers) and only stored per element.
- Geant4 integrates over processes on the fly to get the "total" cross section (even though really each independent process is independently sampling an interaction distance), whereas Shift integrates over elements on the fly and samples a single interaction length.
- During an interaction, Geant4 recalculates all the elemental cross sections for the selected process and samples the element from those. Shift *caches* the elemental cross sections used to calculate the total XS so it doesn't have to recalculate those; it then samples the process from the selected element using the cached total cross section for that element. (This requires the cross sections to balance correctly at every energy, which can be a problem if the process- and total- grids are different or different interpolation schemes are used.)
- Geant4's element-integrated cross sections are tabulated on a fixed log-spaced grid, whereas Shift's cross section grids are all chosen by AMPX and can be pretty fine (and include discontinuities from shell structure in the low-energy regime).

So related to https://github.com/celeritas-project/celeritas/issues/3 we need to make some decisions.
- Do we assume that Geant's pre-tabulation of per-process element-integrated cross sections are sufficiently accurate? (Do we lose any features or edges by approximating with an interpolation and an arbitrary log grid.)
- Can we then assume that per-process per-element cross sections can also be pre-tabulated equally accurately and sampled from?
- Can we also assume the pre-process grids are equal, and construct a unified per-material total cross section to sample from (for discrete processes) with interpolation, then on the fly sample from processes, and then sample the element from the selected process? (This is basically what @whokion suggested.)
- If any/all of these assumptions are invalid, do we cache material- and process-dependent cross sections as we transport, like Shift does?

Unless we can pre-tabulate and ensure the cross sections balance across elements and processes, we will have to (at least temporarily) cache per-element cross sections during interactions, which Geant4 does for EM models by filling up the thread-private `xsec` array. There are a few ways we can approach this:
- For sampling an element after a process is selected, if the element-integrated value is exact we can just accumulate per-element values on the fly to select an element.
- We could preallocate a single "element xs cache" for each particle track, sized to the maximum number of elements in any material. This cache would be used only as an on-the-fly thing for a single process at a time.
- We could cache cross sections for each particle track *and* each process and each element. This could be memory intensive. The plus side is potentially saving cross section reevaluations as a particle moves between volumes.
- We could use an on-the-fly approach where each process uses a stack allocator to reserve storage as needed for sampling. This runs the risk of overflowing if too many particles are in a particularly complicated material.

**Comment by whokion** [comment]
To clarify for Geant4 in the second bullet:  Geant4 uses the "macroscopic" cross section of a process per material (integrated over all elements of a material) for sampling GPIL and selecting a process governing the next step, but does not use "the total cross section of a particle" (i.e., integrated over all processes for a given particle) per material except for the general gamma process recently added.  In the description, the total cross section is equivalently used as the macroscopic cross section per material (which is fine), but should be clearly distinguished from the total cross section of the particle over processes (which was somewhat confusing to me).

As a second thought for how to deal with selecting an atom in an atomic-dependent model, we should at least implement the element cross section evaluation on-the-fly for the first pass (i.e, exactly following the Geant4 approach).  There are several potential issues related to using the pre-tabulated cross sections of models: 1) physics validations as the interpolation is now a two-fold over the particle energy and the atomic number (both are usually non-linear in an atomic-dependent cross section fomula), 2) a related argument on an oversimplification for the final state sampling in a physics model, 3) arguments for performance comparisons (i.e., the CPU version of celeritas is not equivalent to what Geant4 does) and performance itself (i.e., arithmetic vs. memory) even though the on-the-fly approach adds intensity for both.  Of course, the tabulated approach can be explored later as an option (if the approximation is good enough for HEP, then we should also recommend Geant4 to introduce the same approach as an option).

Note on the caching the element cross section per material:  this may not be efficient anyway as the sampling is also depending on the particle energy (which changes in every step for a non-elastic process even within the same volume).

**Comment by sethrj** [comment]
Per today's discussion:
- Shift's assumption that microscopic cross section can always be linearly combined into macroscopic cross section isn't necessarily the case: for some processes/models, microscopic cross sections are functions of the material properties (e.g. electron density).
- Precalculating and linearly interpolating per-material cross sections is probably OK because it's just for sampling distance-to-collision, but trying to interpolate microscopic cross sections for selecting a particular element runs an unacceptable risk of biasing the simulation.
- With these two data points we will always need to calculate microscopic cross sections for on the fly for the selected process.
- The most number of elements in any material in CMS is 15, so it wouldn't be a huge burden to preallocate that much storage for each thread for cross section calculations, as opposed to using a stack allocator.

**Comment by sethrj** [comment]
So action items are:
- [ ] Add accessor for maximum number of elements (or nuclides once we start doing hadronic physcics) for any given material
- [ ] Add temporary elemental cross section storage to the material track view (?) or other suitable continer
- [ ] Add a functor (templated on an `MicroXsEvaluator` class) for calculating cross sections and sampling an element based on the macroscopic xs contribution of that element for the given process

**Comment by sethrj** [comment]
Per our discussion with Mihaly yesterday on the Excalibur call [see meeting minutes](https://docs.google.com/document/d/1ZOdIGuaYJHC9kZ65gG01ea498E9yj-bQVbFq9tSzXnE/edit#heading=h.hqmmvyljmrw7) Geant4 doesn't typically calculate the elemental partial macro cross sections on the fly! It precalculates and tabulates them using the `G4ElementSelector` which is good news for us. We should be able to pull in the microscopic cross sections (or partial macros) from Geant and sample those.

**Comment by whokion** [comment]
Reviewing current (10.7) Geant4 EM models of the standard EM physics list, the use of the element selector (by either SelectRandomAtom(**coupe**, ....) or SelectTargetAtom(**couple**, ...) when the element selector is built during the initialization of a model) replacing the on-the-fly calculation (by SelectRandomAtom(**material,** ....)) in relevant atomic-dependent models was introduced:

BetheHeitler since 10.5
SeltzerBerger since 10.5 
LivermorePhotoEletric: still uses the on-the-fly option
LovermoreRayleigh: has used the element selector from long time ago, but was added to the standard EM physics since 10.4

All other EM models used in celeritas (KN, MollerBhabar, eplusAnnihilation, and MSC) are atomic-independent except that
MollerBhabar uses  SelectRandomAtomNumber(matertial) which does the atomic x-section calculation.

**Comment by whokion** [comment]
Just to clarify: The reason that the PhotoElectric effect model does not use the pre-build table is ,of course, for the purpose of accuracy requirement as the linear interpolation within a fixed bin may not be good enough for most of applications due to resonances in the x-section at the low energy region.

**Comment by sethrj** [comment]
Hah I was just going to ask that! Thanks for the details.

**Comment by whokion** [comment]
For the long term, we may consider to add the x-section calculations for those three models too so that **both options** are supported - moving to the opposite direction to Gean4!  Even though the task may not be a trivial work, it should not take  more than a couple of weeks by one person either.  If the celeritas application does not feed enough FLOPS, ALUs are mostly  idle as most of simulation tasks are memory-bounded tasks.  Even though the on-the-fly calculation for each model is much slower than the pre-built table approach, it may be still worthwhile to mix models with different options together (as FLOPS is nearly free to a certain extent) and to evaluate whether there is any potential gain by mitigating the memory latency/access.  At least, we will provide the more accurate simulation option and understand/measure the computing performance for different cases.  Just IMHO.
