### ISSUE TITLE
Support importing G4GammaGeneralProcess

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#683]
The G4GammaGeneralProcess is a performance enhancement for Geant4 that uses a single "total" cross section (and sampling during a collision) instead of independently sampling several different path lengths for processes. (Celeritas does this by default.) Unfortunately this means the G4VProcess physics table has only a single physics table for cross section instead of one per process, which we need to build our own processes. There may be a way we can reconstruct our needed processes from the gamma general?

**Comment by drbenmorgan** [comment]
Probably worth asking Mihaly Novak (@mnovak42) about this!

**Comment by mnovak42** [comment]
The performance improvements in case of GammaGeneral process comes from the fact, that there is a **single cross section interpolation** at the pre-step point instead of N (assuming N processes for gamma). Then the necessary (at most) N-1 interpolations are done at the post-step point but **only if one of these N interaction happens**. **When** none of these interaction happens, i.e. **post-step point is on boundary**, then these **N-1 cross section evaluation is saved**. 
This is where the performance gain comes and **not from sampling 1 or N step lengths**: in other words, if you evaluate the N cross sections, take their sum and sample a single step length then you won't have much gain.

GammaGeneral-process is a wrapper process:
 - encapsulates the real `G4VProcess` -es that are assigned to gamma 
 - builds its own (rather *tricky*) table of macroscopic cross sections that is the sum of all individual process cross sections 
 - the encapsulated sub-processes provides their cross section for this 

Note, that summing up the macroscopic cross sections from all gamma processes needs to be done by care as not all cross sections are smooth and there are hard limits in energy. In order to get something that is interpolable different sub-tables needs to be build at different energy ranges. This is why the internal cross section table and process probabilities are *tricky*. 

Are you sure that you build a single table? Not having the individual cross section tables per-processes and you evaluate all at the pre-step point then sum them up before sampling the single step length till the next (any) interactions?

**Comment by sethrj** [comment]
Aha, we do *not* precalculate the total cross section summed over processes, but we *do* calculate it on the fly. From that total, we sample a single physics interaction length (decrementing a single mean-free-paths counter), and upon interaction we select the process. So we're halfway in between the Geant4 process-dependent-interaction-length approach and the full GammaGeneral approach.

Indeed you're right that building total macroscopic cross sections are tricky: I think we'd like to move that direction (especially if we add neutron physics), as the reduced memory bandwidth can be a substantial boost for GPUs as well as CPUs. The ExaSMR/Shift codes rely completely on process-integrated (but separate by element/nuclide/temperature) cross sections, and we have a few algorithms for accelerating the energy lookup for those values.

> encapsulates the real G4VProcess -es that are assigned to gamma

Thanks for the pointer to this: it looks like we should be able to use `G4GammaGeneralProcess::GetEmProcess` to pull out the processes ourselves and then create the physics from that. I appreciate the comments!
