### ISSUE TITLE
Fix or output "lost energy" warnings on boundaries

### ISSUE THREAD

**Issue by sethrj** [celeritas-project/celeritas#891]
@whokion reports seeing numerous errors during sensitive detector callback. A JSON output entry of expected volumes and associated points would help debugging potential geometry issues.

**Comment by whokion** [comment]
A typical warning and an error message even with the `simple-cms.gdml `and without a magnetic field (i.e, `zero field`) are
```
celeritas/src/accel/detail/HitProcessor.cc:352: warning: Failed to bump navigation state up to a distance of 1 [mm]
celeritas/src/accel/detail/HitProcessor.cc:359: error: expected step point at {-1192.9924132862, 373.1877568188, 
965.16719905548} [mm] along {-0.054506464560737, -0.19953890346168, -0.9783727670609} to be in logical volume 
"si_tracker"@0x1d19b50 (ID=1) but navigation gives {{pv='em_calorimeter_pv', lv=2='em_calorimeter'}}: omitting energy 
deposition of 0.0553134 [MeV]
```
So, it seems that this error is due to neither a volume overlap nor a side effect of the propagation in a field.  For this example,  the hit (or the post step position) is at R=1249.9999999991517 [mm] which is inside the si_tracker (rmax="1249.9999999999") and before the em_calorimeter (rmin="1250").

**Comment by sethrj** [comment]
Interesting... it's just fuzziness on the boundary, and the "bump" we attempt is further into the EM calorimeter (since the track is exiting the SI tracker). Maybe we also need to try bumping in the opposite direction as well...

**Comment by whokion** [comment]
The bumping 1 [mm] along the momentum direction does not help for this case, as the resultant R=1249.9924653494668 (i.e, the particle still remain in the si_tracker after bumping along the momentum direction by 1 mm).  An alternative my be to bump along the position direction keeping the momentum direction (which we cannot change), but then the particle will re-enter to the si_tracker again in the next step.
