### ISSUE TITLE
Submit paper for CHEP

### ISSUE THREAD

**Issue by tmdelellis** [celeritas-project/celeritas#94]
The site for the CHEP conference is: https://indico.cern.ch/event/948465.  The full submission consists of an abstract and a paper of 6 to 10 pages.

Paper submission opens:                   1 December 2020
Registration opens:                            1 February 2021
Paper submission closes:                  28 February 2021
Paper acceptance notifications:        15 April 2021
Conference:                                         17-21 May 2021
Final paper revision for publication:  25 June 2021

**Comment by sethrj** [comment]
As discussed in today's meeting, we're going to try to get a photon+electron demo app that uses Moller scattering (#132) and photoelectric effect (#113) with atomic relaxation (#134) to demonstrate the cycle of secondary production and track construction from those secondaries.

**Comment by sethrj** [comment]
Today's discussion about the paper: we're going to present an overall view of the Celeritas code base and goals, including:
- External integration with other HEP packages such as ROOT, HepMC3, and VecGeom;
- Description of the current components and planned algorithms in Celeritas;
- Detailed description of the data model that we use to support heterogeneous data management and kernels; and
- Demonstration of how the Celeritas data model allows rapid prototyping of on-device performance improvement without touching any of the computational kernels.

This last bullet will use the existing Klein-Nishina demo app (or we could use some other single model) and try one or more of:
- Load the RNG state into local memory on construction of the RNG engine, then write it back out on destruction
- Modify the `Pie` traits so that for `const_reference, device` instances where `T` is primitive data, the `operator[]` uses the special `__ldg` function to cache the value as read-only
- Restructure the particle state so that it's a struct of arrays (energy, particle ID) rather than array of structs

@tmdelellis @pcanal

**Comment by tmdelellis** [comment]
Template with rough outline pushed to `celeritas-docs`, 491eb48b.

**Comment by sethrj** [comment]
Submitted paper: [celeritas-chep-2021.pdf](https://github.com/celeritas-project/celeritas/files/6055340/celeritas-chep-2021.pdf)

https://indico.cern.ch/event/948465/abstracts/122456/
